---
abstract: 'Returns your ip address using L<http://perltricks.com/services/echo_ip>'
author:
  - 'David Farrell <dfarrell@cpan.org>'
build_requires:
  Test::More: '0'
  Test::RequiresInternet: '0.03'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.034, CPAN::Meta::Converter version 2.150001'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-PerlTricksIP
requires:
  Exporter: '0'
  HTTP::Tiny: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
version: '0.01'
